# Generated by Django 5.0.14 on 2025-05-07 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CasoJudicial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.PositiveIntegerField()),
                ('expediente', models.CharField(max_length=100)),
                ('sede', models.CharField(max_length=100)),
                ('especialidad', models.CharField(max_length=100)),
                ('materia', models.CharField(max_length=100)),
                ('juzgado', models.CharField(max_length=100)),
                ('demandante', models.CharField(max_length=255)),
                ('demandado', models.CharField(max_length=255)),
                ('anio_inicio', models.PositiveIntegerField()),
                ('representante', models.BooleanField()),
            ],
        ),
    ]
