# Generated by Django 5.0.14 on 2025-05-07 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_expediente', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casojudicial',
            name='representante',
            field=models.CharField(choices=[('demandante', 'Demandante'), ('demandado', 'Demandado')], max_length=20),
        ),
    ]
