# Generated by Django 5.0.14 on 2025-05-07 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_expediente', '0002_alter_casojudicial_representante'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casojudicial',
            name='anio_inicio',
            field=models.CharField(max_length=4),
        ),
    ]
