# Generated by Django 5.0.14 on 2025-05-08 16:44

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_expediente', '0004_alter_casojudicial_anio_inicio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seguimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resolucion', models.TextField()),
                ('fecha_seguimiento', models.DateField()),
                ('seguimiento', models.TextField()),
                ('fecha_pendiente', models.DateField(blank=True, null=True)),
                ('pendiente', models.TextField(blank=True)),
                ('responsable', models.CharField(max_length=255)),
                ('estado', models.CharField(choices=[('En proceso', 'En Proceso'), ('Finalizado', 'Finalizado')], default='en_proceso', max_length=20)),
                ('fecha_registro', models.DateTimeField(default=django.utils.timezone.now)),
                ('caso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seguimientos', to='control_expediente.casojudicial')),
            ],
        ),
        migrations.CreateModel(
            name='Gasto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('detalle', models.TextField()),
                ('sustento', models.TextField(blank=True)),
                ('pdf', models.FileField(blank=True, null=True, upload_to='gastos_expediente/')),
                ('gastos_soles', models.DecimalField(decimal_places=2, max_digits=10)),
                ('gastos_dolares', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_registro', models.DateTimeField(default=django.utils.timezone.now)),
                ('seguimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gastos', to='control_expediente.seguimiento')),
            ],
        ),
    ]
