# Generated by Django 5.0.14 on 2025-05-13 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_expediente', '0005_seguimiento_gasto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seguimiento',
            name='fecha_registro',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
