# Generated by Django 5.0.14 on 2025-05-12 19:52

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_expediente', '0005_seguimiento_gasto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seguimiento',
            name='fecha_registro',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.CreateModel(
            name='GastoPresentacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('detalle', models.TextField()),
                ('sustento', models.TextField(blank=True)),
                ('pdf', models.FileField(blank=True, null=True, upload_to='gastos_expediente/')),
                ('gastos_soles', models.DecimalField(decimal_places=2, max_digits=10)),
                ('gastos_dolares', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_registro', models.DateTimeField(default=django.utils.timezone.now)),
                ('seguimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gastos_presentaciones', to='control_expediente.seguimiento')),
            ],
        ),
        migrations.CreateModel(
            name='Presentacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('presentado', models.TextField()),
                ('escrito', models.CharField(max_length=255)),
                ('caso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presentaciones', to='control_expediente.casojudicial')),
            ],
        ),
    ]
