# Generated by Django 5.0.14 on 2025-05-12 21:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_expediente', '0006_alter_seguimiento_fecha_registro_gastopresentacion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gastopresentacion',
            name='seguimiento',
        ),
        migrations.AddField(
            model_name='gastopresentacion',
            name='presentacion',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='gastos_presentaciones', to='control_expediente.presentacion'),
            preserve_default=False,
        ),
    ]
