# Generated by Django 5.0.14 on 2025-05-12 22:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_expediente', '0008_alter_gastopresentacion_presentacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gastopresentacion',
            name='presentacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gastos_presentaciones', to='control_expediente.presentacion'),
        ),
    ]
