# Generated by Django 5.0.14 on 2025-05-13 03:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('control_expediente', '0006_alter_seguimiento_fecha_registro'),
        ('control_expediente', '0009_alter_gastopresentacion_presentacion'),
    ]

    operations = [
    ]
