# Generated by Django 5.0.14 on 2025-05-13 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_expediente', '0010_merge_20250512_2250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gasto',
            name='gastos_dolares',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
