# Generated by Django 5.0.14 on 2025-05-13 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_expediente', '0011_alter_gasto_gastos_dolares'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seguimiento',
            name='responsable',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
