# Generated by Django 5.0.14 on 2025-05-14 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_expediente', '0012_alter_seguimiento_responsable'),
    ]

    operations = [
        migrations.AddField(
            model_name='seguimiento',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to='gastos_expediente/'),
        ),
    ]
