# Generated by Django 5.0.14 on 2025-05-14 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_expediente', '0013_seguimiento_pdf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seguimiento',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to='seguimiento/'),
        ),
    ]
