# Generated by Django 5.0.14 on 2025-05-15 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_expediente', '0014_alter_seguimiento_pdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='gasto',
            name='codigo_pago',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
