# Generated by Django 5.0.14 on 2025-05-18 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_expediente', '0015_gasto_codigo_pago'),
    ]

    operations = [
        migrations.AddField(
            model_name='seguimiento',
            name='inter',
            field=models.BooleanField(default=False),
        ),
    ]
