# Generated by Django 5.0.14 on 2025-05-21 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_expediente', '0017_seguimiento_tlf_juzgado_alter_seguimiento_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='seguimiento',
            name='editor',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
