# Generated by Django 5.0.14 on 2025-05-21 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_expediente', '0018_seguimiento_editor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seguimiento',
            name='tlf_juzgado',
        ),
        migrations.AddField(
            model_name='casojudicial',
            name='tlf_juzgado',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
