# Generated by Django 5.0.14 on 2025-05-21 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_expediente', '0021_seguimiento_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seguimiento',
            name='resolucion',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
