# Generated by Django 5.0.14 on 2025-05-21 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_expediente', '0023_alter_seguimiento_responsable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seguimiento',
            name='fecha_seguimiento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='seguimiento',
            name='responsable',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
