# Generated by Django 5.0.14 on 2025-05-22 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_expediente', '0024_alter_seguimiento_fecha_seguimiento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casojudicial',
            name='sede',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
