# Generated by Django 5.0.14 on 2025-05-22 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_expediente', '0025_alter_casojudicial_sede'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casojudicial',
            name='codigo',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
