# Generated by Django 5.0.14 on 2025-05-23 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_expediente', '0030_alter_casojudicial_especialidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seguimiento',
            name='inter',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
