# Generated by Django 5.0.14 on 2025-06-02 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_expediente', '0031_alter_seguimiento_inter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gasto',
            name='detalle',
            field=models.TextField(blank=True, null=True),
        ),
    ]
