# Generated by Django 5.0.14 on 2025-06-04 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_expediente', '0032_alter_gasto_detalle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seguimiento',
            name='estado',
            field=models.CharField(choices=[('En proceso', 'En Proceso'), ('Finalizado', 'Finalizado'), ('Presentado', 'Presentado'), ('Notificado', 'Notificado'), ('Otros', 'Otros')], default='en_proceso', max_length=20),
        ),
    ]
