# Generated by Django 5.0.14 on 2025-06-05 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_expediente', '0034_alter_casojudicial_representante'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casojudicial',
            name='representante',
            field=models.CharField(choices=[('Demandante', 'Demandante'), ('Demandado', 'Demandado'), ('Martillero', 'Martillero')], max_length=20),
        ),
    ]
