# Generated by Django 5.0.14 on 2025-06-24 16:23

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('control_expediente', '0036_registroactividad'),
    ]

    operations = [
        migrations.RenameField(
            model_name='casojudicial',
            old_name='tlf_juzgado',
            new_name='pendiente',
        ),
        migrations.RemoveField(
            model_name='casojudicial',
            name='anio_inicio',
        ),
        migrations.AlterField(
            model_name='seguimiento',
            name='seguimiento',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
