# Generated by Django 5.0.14 on 2025-06-25 13:08

import ckeditor.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_expediente', '0037_rename_tlf_juzgado_casojudicial_pendiente_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='gasto',
            name='editor',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='gasto',
            name='fecha_registro2',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='gasto',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seguimientos_gasto2', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='casojudicial',
            name='pendiente',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='seguimiento',
            name='pendiente',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
