# Generated by Django 5.0.14 on 2025-06-25 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('control_expediente', '0038_gasto_editor_gasto_fecha_registro2_gasto_usuario_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gasto',
            name='editor',
        ),
        migrations.RemoveField(
            model_name='gasto',
            name='fecha_registro2',
        ),
        migrations.RemoveField(
            model_name='gasto',
            name='usuario',
        ),
    ]
