# Generated by Django 5.0.14 on 2025-07-09 11:50

import ckeditor.fields
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_expediente', '0039_remove_gasto_editor_remove_gasto_fecha_registro2_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CarpetaFiscal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(blank=True, max_length=100, null=True)),
                ('carpeta_fiscal', models.CharField(blank=True, max_length=100, null=True)),
                ('pendiente', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('delito', models.CharField(blank=True, max_length=100, null=True)),
                ('fiscalia', models.CharField(blank=True, max_length=100, null=True)),
                ('demandante', models.CharField(max_length=255)),
                ('demandado', models.CharField(max_length=255)),
                ('sede', models.CharField(blank=True, max_length=100, null=True)),
                ('especialidad', models.CharField(blank=True, max_length=100, null=True)),
                ('representante', models.CharField(choices=[('Demandante', 'Demandante'), ('Demandado', 'Demandado'), ('Martillero', 'Martillero')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='SeguimientoFiscal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resolucion', models.CharField(blank=True, max_length=255, null=True)),
                ('fecha_seguimiento', models.DateField(blank=True, null=True)),
                ('seguimiento', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('fecha_pendiente', models.DateField(blank=True, null=True)),
                ('pendiente', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('responsable', models.CharField(blank=True, max_length=255, null=True)),
                ('estado', models.CharField(choices=[('En proceso', 'En Proceso'), ('Finalizado', 'Finalizado'), ('Presentado', 'Presentado'), ('Notificado', 'Notificado'), ('Otros', 'Otros')], default='en_proceso', max_length=20)),
                ('pdf', models.FileField(blank=True, null=True, upload_to='seguimiento/')),
                ('inter', models.BooleanField(blank=True, null=True)),
                ('fecha_registro', models.DateTimeField(auto_now=True)),
                ('editor', models.CharField(blank=True, max_length=255, null=True)),
                ('caso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seguimientos_penal', to='control_expediente.carpetafiscal')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seguimientos_creados_fiscal', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GastoFiscal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('detalle', models.TextField(blank=True, null=True)),
                ('sustento', models.TextField(blank=True)),
                ('pdf', models.FileField(blank=True, null=True, upload_to='gastos_expediente/')),
                ('codigo_pago', models.CharField(blank=True, max_length=255, null=True)),
                ('gastos_soles', models.DecimalField(decimal_places=2, max_digits=10)),
                ('gastos_dolares', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('fecha_registro', models.DateTimeField(default=django.utils.timezone.now)),
                ('seguimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gastos_fiscal', to='control_expediente.seguimientofiscal')),
            ],
        ),
    ]
