# Generated by Django 5.0.14 on 2025-07-14 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_expediente', '0040_carpetafiscal_seguimientofiscal_gastofiscal'),
    ]

    operations = [
        migrations.AddField(
            model_name='casojudicial',
            name='fecha_compromiso',
            field=models.DateField(blank=True, null=True),
        ),
    ]
