# Generated by Django 5.0.14 on 2025-07-21 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_expediente', '0041_casojudicial_fecha_compromiso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seguimiento',
            name='pdf',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to='seguimiento/'),
        ),
    ]
