# Generated by Django 5.0.14 on 2025-07-30 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_expediente', '0042_alter_seguimiento_pdf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gasto',
            name='detalle',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='gastofiscal',
            name='detalle',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
