# Generated by Django 5.0.14 on 2025-08-09 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('control_expediente', '0043_alter_gasto_detalle_alter_gastofiscal_detalle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seguimiento',
            name='inter',
        ),
    ]
