# Generated by Django 5.0.14 on 2025-09-30 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_expediente', '0044_remove_seguimiento_inter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gastofiscal',
            name='gastos_soles',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
