# Generated by Django 5.0.14 on 2025-09-30 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_expediente', '0045_alter_gastofiscal_gastos_soles'),
    ]

    operations = [
        migrations.AddField(
            model_name='gastofiscal',
            name='editor',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
