# Generated by Django 5.0.14 on 2025-09-30 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_expediente', '0046_gastofiscal_editor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='presentacion',
            name='caso',
        ),
        migrations.AddField(
            model_name='gasto',
            name='editor',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.DeleteModel(
            name='GastoPresentacion',
        ),
        migrations.DeleteModel(
            name='Presentacion',
        ),
    ]
