# Generated by Django 5.0.14 on 2025-09-30 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_expediente', '0047_remove_presentacion_caso_gasto_editor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gasto',
            name='gastos_soles',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
