# Generated by Django 5.0.14 on 2025-09-30 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_expediente', '0048_alter_gasto_gastos_soles'),
    ]

    operations = [
        migrations.AddField(
            model_name='gasto',
            name='estado',
            field=models.CharField(blank=True, choices=[('Caja Chica', 'Caja Chica'), ('Externo', 'Externo')], default='Externo', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='gasto',
            name='fecha_modificacion',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='gasto',
            name='fecha_registro',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='seguimiento',
            name='estado',
            field=models.CharField(choices=[('En proceso', 'En Proceso'), ('Finalizado', 'Finalizado'), ('Presentado', 'Presentado'), ('Notificado', 'Notificado'), ('Otros', 'Otros')], default='Finalizado', max_length=20),
        ),
    ]
