# Generated by Django 5.0.14 on 2025-09-30 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('control_expediente', '0049_gasto_estado_gasto_fecha_modificacion_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gasto',
            old_name='estado',
            new_name='tipo_gasto',
        ),
    ]
