# Generated by Django 5.0.14 on 2025-09-30 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_expediente', '0050_rename_estado_gasto_tipo_gasto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gasto',
            name='tipo_gasto',
            field=models.CharField(choices=[('Caja Chica', 'Caja Chica'), ('Externo', 'Externo')], default='Externo', max_length=20),
        ),
    ]
