# Generated by Django 5.0.14 on 2025-10-08 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('control_expediente', '0051_alter_gasto_tipo_gasto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gasto',
            name='tipo_gasto',
        ),
    ]
