# Generated by Django 5.0.14 on 2025-10-12 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_expediente', '0053_casojudicial_responsable'),
    ]

    operations = [
        migrations.AddField(
            model_name='casojudicial',
            name='fecha_alerta',
            field=models.DateField(blank=True, null=True),
        ),
    ]
