# Generated by Django 5.0.14 on 2025-10-13 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_expediente', '0054_casojudicial_fecha_alerta'),
    ]

    operations = [
        migrations.AddField(
            model_name='seguimiento',
            name='fecha_alerta',
            field=models.DateField(blank=True, null=True),
        ),
    ]
