# Generated by Django 5.0.14 on 2025-10-13 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('control_expediente', '0055_seguimiento_fecha_alerta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='casojudicial',
            name='fecha_alerta',
        ),
    ]
