# Generated by Django 5.0.14 on 2025-10-13 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_expediente', '0056_remove_casojudicial_fecha_alerta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seguimientofiscal',
            name='usuario',
        ),
        migrations.AddField(
            model_name='seguimientofiscal',
            name='fecha_alerta',
            field=models.DateField(blank=True, null=True),
        ),
    ]
