# Generated by Django 5.0.14 on 2025-10-13 12:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_expediente', '0058_seguimientofiscal_usuario'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='carpetafiscal',
            name='responsable',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 2}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='casos_asignados_carpeta_fiscal', to=settings.AUTH_USER_MODEL, verbose_name='Responsable (Área Legal)'),
        ),
    ]
