# Generated by Django 5.0.14 on 2025-10-16 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_expediente', '0059_carpetafiscal_responsable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gasto',
            name='pdf',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to='gastos_expediente/'),
        ),
        migrations.AlterField(
            model_name='gastofiscal',
            name='pdf',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to='gastos_expediente/'),
        ),
        migrations.AlterField(
            model_name='seguimientofiscal',
            name='pdf',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to='seguimiento/'),
        ),
    ]
