# Generated by Django 5.0.14 on 2025-10-23 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_expediente', '0060_alter_gasto_pdf_alter_gastofiscal_pdf_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='casojudicial',
            name='concluido',
            field=models.BooleanField(default=True, help_text='True => Activo, False => Concluido'),
        ),
    ]
