# Generated by Django 5.0.14 on 2025-10-24 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_expediente', '0061_casojudicial_concluido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casojudicial',
            name='juzgado',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='casojudicial',
            name='materia',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
