# Generated by Django 5.0.14 on 2025-10-27 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_expediente', '0062_alter_casojudicial_juzgado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='carpetafiscal',
            name='concluido',
            field=models.BooleanField(default=True, help_text='True => Activo, False => Concluido'),
        ),
    ]
