# Generated by Django 5.0.14 on 2025-11-13 17:08

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('control_expediente', '0063_carpetafiscal_concluido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seguimiento',
            name='pendiente',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='seguimiento',
            name='seguimiento',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
    ]
