# Generated by Django 5.0.14 on 2025-06-02 16:12

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tramite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(blank=True, max_length=100, null=True)),
                ('sede', models.CharField(blank=True, max_length=100, null=True)),
                ('especialidad', models.CharField(blank=True, max_length=100, null=True)),
                ('materia', models.CharField(blank=True, max_length=100, null=True)),
                ('juzgado', models.CharField(blank=True, max_length=100, null=True)),
                ('demandante', models.CharField(max_length=255)),
                ('demandado', models.CharField(max_length=255)),
                ('anio_inicio', models.CharField(blank=True, max_length=4, null=True)),
                ('representante', models.CharField(choices=[('demandante', 'Demandante'), ('demandado', 'Demandado')], max_length=20)),
                ('tlf_juzgado', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SeguimientoTramite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resolucion', models.CharField(blank=True, max_length=255, null=True)),
                ('fecha_seguimiento', models.DateField(blank=True, null=True)),
                ('seguimiento', models.TextField()),
                ('fecha_pendiente', models.DateField(blank=True, null=True)),
                ('pendiente', models.TextField(blank=True)),
                ('responsable', models.CharField(blank=True, max_length=255, null=True)),
                ('estado', models.CharField(choices=[('En proceso', 'En Proceso'), ('Finalizado', 'Finalizado'), ('Presentado', 'Presentado')], default='en_proceso', max_length=20)),
                ('pdf', models.FileField(blank=True, null=True, upload_to='seguimiento/')),
                ('inter', models.BooleanField(blank=True, null=True)),
                ('fecha_registro', models.DateTimeField(auto_now=True)),
                ('editor', models.CharField(blank=True, max_length=255, null=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seguimientos_tramite_creados', to=settings.AUTH_USER_MODEL)),
                ('caso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seguimientos_tramites', to='tramites.tramite')),
            ],
        ),
        migrations.CreateModel(
            name='Gasto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('detalle', models.TextField(blank=True, null=True)),
                ('sustento', models.TextField(blank=True)),
                ('pdf', models.FileField(blank=True, null=True, upload_to='gastos_expediente/')),
                ('codigo_pago', models.CharField(blank=True, max_length=255, null=True)),
                ('gastos_soles', models.DecimalField(decimal_places=2, max_digits=10)),
                ('gastos_dolares', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('fecha_registro', models.DateTimeField(default=django.utils.timezone.now)),
                ('seguimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gastos_tramites', to='tramites.seguimientotramite')),
            ],
        ),
    ]
