# Generated by Django 5.0.14 on 2025-06-03 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tramites', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Gasto',
            new_name='GastoTramite',
        ),
    ]
