# Generated by Django 5.0.14 on 2025-06-04 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tramites', '0002_rename_gasto_gastotramite'),
    ]

    operations = [
        migrations.AddField(
            model_name='tramite',
            name='tramite',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
