# Generated by Django 5.0.14 on 2025-06-04 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tramites', '0003_tramite_tramite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tramite',
            name='codigo',
        ),
        migrations.RemoveField(
            model_name='tramite',
            name='representante',
        ),
        migrations.AddField(
            model_name='tramite',
            name='fecha',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tramite',
            name='tramite',
            field=models.CharField(choices=[('Administrativo', 'Administrativo'), ('Municipal', 'Municipal'), ('Identificación', 'Identificación (RENIEC, otros)'), ('Tributario', 'Tributario'), ('Notarial', 'Notarial'), ('Registral', 'Registral'), ('Otros', 'Otros')], default=1, max_length=30),
            preserve_default=False,
        ),
    ]
