# Generated by Django 5.0.14 on 2025-06-04 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tramites', '0004_remove_tramite_codigo_remove_tramite_representante_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tramite',
            old_name='especialidad',
            new_name='descripcion',
        ),
        migrations.RenameField(
            model_name='tramite',
            old_name='juzgado',
            new_name='destinatario',
        ),
        migrations.RenameField(
            model_name='tramite',
            old_name='materia',
            new_name='responsable',
        ),
        migrations.RemoveField(
            model_name='seguimientotramite',
            name='resolucion',
        ),
        migrations.RemoveField(
            model_name='tramite',
            name='anio_inicio',
        ),
        migrations.RemoveField(
            model_name='tramite',
            name='demandado',
        ),
        migrations.RemoveField(
            model_name='tramite',
            name='demandante',
        ),
        migrations.RemoveField(
            model_name='tramite',
            name='sede',
        ),
        migrations.RemoveField(
            model_name='tramite',
            name='tlf_juzgado',
        ),
        migrations.AddField(
            model_name='tramite',
            name='tramite_tipo',
            field=models.CharField(choices=[('Administrativo', 'Administrativo'), ('Municipal', 'Municipal'), ('Identificación', 'Identificación (RENIEC, otros)'), ('Tributario', 'Tributario'), ('Notarial', 'Notarial'), ('Registral', 'Registral'), ('Otros', 'Otros')], default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tramite',
            name='tramite',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
