# Generated by Django 5.0.14 on 2025-06-04 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tramites', '0005_rename_especialidad_tramite_descripcion_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tramite',
            old_name='tramite',
            new_name='partes_intervinientes',
        ),
        migrations.AlterField(
            model_name='tramite',
            name='tramite_tipo',
            field=models.CharField(choices=[('Administrativo', 'Administrativo'), ('Municipal', 'Municipal'), ('Identificación (RENIEC, otros)', 'Identificación (RENIEC, otros)'), ('Tributario', 'Tributario'), ('Notarial', 'Notarial'), ('Registral', 'Registral'), ('Otros', 'Otros')], max_length=30),
        ),
    ]
