# Generated by Django 5.0.14 on 2025-06-04 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tramites', '0006_rename_tramite_tramite_partes_intervinientes_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tramite',
            old_name='descripcion',
            new_name='sumilla',
        ),
    ]
