# Generated by Django 5.0.14 on 2025-06-04 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tramites', '0007_rename_descripcion_tramite_sumilla'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tramite',
            name='tramite_tipo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
