# Generated by Django 5.0.14 on 2025-06-05 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tramites', '0008_alter_tramite_tramite_tipo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tramite',
            name='responsable',
        ),
    ]
