# Generated by Django 5.0.14 on 2025-06-05 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tramites', '0009_remove_tramite_responsable'),
    ]

    operations = [
        migrations.AddField(
            model_name='tramite',
            name='responsable',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
