# Generated by Django 5.0.14 on 2025-06-05 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tramites', '0010_tramite_responsable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tramite',
            name='tramite_tipo',
            field=models.CharField(max_length=100),
        ),
    ]
