# Generated by Django 5.0.14 on 2025-06-08 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tramites', '0011_alter_tramite_tramite_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tramite',
            name='tramite_tipo',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
