# Generated by Django 5.0.14 on 2025-06-25 13:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tramites', '0012_alter_tramite_tramite_tipo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='gastotramite',
            name='editor',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='gastotramite',
            name='fecha_registro2',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='gastotramite',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seguimientos_gasto2', to=settings.AUTH_USER_MODEL),
        ),
    ]
