# Generated by Django 5.0.14 on 2025-06-25 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tramites', '0013_gastotramite_editor_gastotramite_fecha_registro2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tramite',
            name='sumilla',
            field=models.TextField(blank=True, null=True),
        ),
    ]
