# Generated by Django 5.0.14 on 2025-07-06 21:16

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tramites', '0014_alter_tramite_sumilla'),
    ]

    operations = [
        migrations.AddField(
            model_name='tramite',
            name='pendiente',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='seguimientotramite',
            name='pendiente',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
