# Generated by Django 5.0.14 on 2025-09-30 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tramites', '0015_tramite_pendiente_alter_seguimientotramite_pendiente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gastotramite',
            name='gastos_soles',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
