# Generated by Django 5.0.14 on 2025-10-10 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tramites', '0016_alter_gastotramite_gastos_soles'),
    ]

    operations = [
        migrations.AddField(
            model_name='tramite',
            name='kardex',
            field=models.CharField(blank=True, editable=False, max_length=15, null=True, unique=True),
        ),
    ]
