# Generated by Django 5.0.14 on 2025-10-10 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tramites', '0018_alter_tramite_kardex'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tramite',
            name='kardex',
            field=models.CharField(blank=True, editable=False, max_length=15, null=True, unique=True),
        ),
    ]
