# Generated by Django 5.0.14 on 2025-10-13 15:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tramites', '0019_alter_tramite_kardex'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='tramite',
            name='responsable2',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 2}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='casos_asignados_tramite', to=settings.AUTH_USER_MODEL, verbose_name='Responsable (Área Legal)'),
        ),
    ]
