# Generated by Django 5.0.14 on 2025-10-13 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tramites', '0020_tramite_responsable2'),
    ]

    operations = [
        migrations.AddField(
            model_name='seguimientotramite',
            name='fecha_alerta',
            field=models.DateField(blank=True, null=True),
        ),
    ]
