# Generated by Django 5.0.14 on 2025-10-13 16:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tramites', '0021_seguimientotramite_fecha_alerta'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='tramite',
            name='responsable2',
            field=models.ForeignKey(blank=True, limit_choices_to=models.Q(('username', 'user8'), _negated=True), null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='casos_asignados_tramite', to=settings.AUTH_USER_MODEL, verbose_name='Responsable (Área Legal)'),
        ),
    ]
