# Generated by Django 5.0.14 on 2025-10-16 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tramites', '0022_alter_tramite_responsable2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seguimientotramite',
            name='pdf',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to='seguimiento/'),
        ),
    ]
