# Generated by Django 5.0.14 on 2025-10-31 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tramites', '0023_alter_seguimientotramite_pdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='tramite',
            name='concluido',
            field=models.BooleanField(default=True, help_text='True => Activo, False => Concluido'),
        ),
    ]
