# Generated by Django 5.0.14 on 2025-10-31 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tramites', '0024_tramite_concluido'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tramite',
            name='responsable',
        ),
    ]
