# Generated by Django 5.0.14 on 2025-11-13 11:33

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tramites', '0025_remove_tramite_responsable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tramite',
            name='pendiente',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tramite',
            name='sumilla',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
    ]
