# Generated by Django 5.0.14 on 2025-11-13 17:08

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tramites', '0026_alter_tramite_pendiente_alter_tramite_sumilla'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seguimientotramite',
            name='pendiente',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='seguimientotramite',
            name='seguimiento',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
    ]
