# Generated by Django 5.0.14 on 2025-04-28 04:30

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CantaCallao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('fecha', models.DateField()),
                ('concepto', models.CharField(max_length=100)),
                ('detalle', models.TextField(blank=True, null=True, validators=[django.core.validators.MaxLengthValidator(100)])),
                ('referencia', models.CharField(blank=True, max_length=100, null=True)),
                ('monto1', models.CharField(blank=True, max_length=10, null=True)),
                ('monto2', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CentroDeCostos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='GastoN1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('fecha', models.DateField(blank=True, null=True)),
                ('detalle', models.TextField(blank=True, null=True)),
                ('referencia', models.CharField(blank=True, max_length=255, null=True)),
                ('pdf', models.FileField(blank=True, max_length=255, null=True, upload_to='gastos')),
                ('monto_soles', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('monto_dolares', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('actividad', models.CharField(blank=True, max_length=255, null=True)),
                ('tipo_gasto', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='GastoN10',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('fecha', models.DateField(blank=True, null=True)),
                ('detalle', models.TextField(blank=True, null=True)),
                ('referencia', models.CharField(blank=True, max_length=255, null=True)),
                ('pdf', models.FileField(blank=True, max_length=255, null=True, upload_to='gastos')),
                ('monto_soles', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('monto_dolares', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('actividad', models.CharField(blank=True, max_length=255, null=True)),
                ('tipo_gasto', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='GastoN2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('fecha', models.DateField(blank=True, null=True)),
                ('detalle', models.TextField(blank=True, null=True)),
                ('referencia', models.CharField(blank=True, max_length=255, null=True)),
                ('pdf', models.FileField(blank=True, max_length=255, null=True, upload_to='gastos')),
                ('monto_soles', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('monto_dolares', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('actividad', models.CharField(blank=True, max_length=255, null=True)),
                ('tipo_gasto', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='GastoN3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('fecha', models.DateField(blank=True, null=True)),
                ('detalle', models.TextField(blank=True, null=True)),
                ('referencia', models.CharField(blank=True, max_length=255, null=True)),
                ('pdf', models.FileField(blank=True, max_length=255, null=True, upload_to='gastos')),
                ('monto_soles', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('monto_dolares', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('actividad', models.CharField(blank=True, max_length=255, null=True)),
                ('tipo_gasto', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='GastoN4',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('fecha', models.DateField(blank=True, null=True)),
                ('detalle', models.TextField(blank=True, null=True)),
                ('referencia', models.CharField(blank=True, max_length=255, null=True)),
                ('pdf', models.FileField(blank=True, max_length=255, null=True, upload_to='gastos')),
                ('monto_soles', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('monto_dolares', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('actividad', models.CharField(blank=True, max_length=255, null=True)),
                ('tipo_gasto', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='GastoN5',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('fecha', models.DateField(blank=True, null=True)),
                ('detalle', models.TextField(blank=True, null=True)),
                ('referencia', models.CharField(blank=True, max_length=255, null=True)),
                ('pdf', models.FileField(blank=True, max_length=255, null=True, upload_to='gastos')),
                ('monto_soles', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('monto_dolares', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('actividad', models.CharField(blank=True, max_length=255, null=True)),
                ('tipo_gasto', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='GastoN6',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('fecha', models.DateField(blank=True, null=True)),
                ('detalle', models.TextField(blank=True, null=True)),
                ('referencia', models.CharField(blank=True, max_length=255, null=True)),
                ('pdf', models.FileField(blank=True, max_length=255, null=True, upload_to='gastos')),
                ('monto_soles', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('monto_dolares', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('actividad', models.CharField(blank=True, max_length=255, null=True)),
                ('tipo_gasto', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='GastoN7',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('fecha', models.DateField(blank=True, null=True)),
                ('detalle', models.TextField(blank=True, null=True)),
                ('referencia', models.CharField(blank=True, max_length=255, null=True)),
                ('pdf', models.FileField(blank=True, max_length=255, null=True, upload_to='gastos')),
                ('monto_soles', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('monto_dolares', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('actividad', models.CharField(blank=True, max_length=255, null=True)),
                ('tipo_gasto', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='GastoN8',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('fecha', models.DateField(blank=True, null=True)),
                ('detalle', models.TextField(blank=True, null=True)),
                ('referencia', models.CharField(blank=True, max_length=255, null=True)),
                ('pdf', models.FileField(blank=True, max_length=255, null=True, upload_to='gastos')),
                ('monto_soles', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('monto_dolares', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('actividad', models.CharField(blank=True, max_length=255, null=True)),
                ('tipo_gasto', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='GastoN9',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('fecha', models.DateField(blank=True, null=True)),
                ('detalle', models.TextField(blank=True, null=True)),
                ('referencia', models.CharField(blank=True, max_length=255, null=True)),
                ('pdf', models.FileField(blank=True, max_length=255, null=True, upload_to='gastos')),
                ('monto_soles', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('monto_dolares', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('actividad', models.CharField(blank=True, max_length=255, null=True)),
                ('tipo_gasto', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='NuevoGasto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=50, null=True)),
                ('url', models.CharField(blank=True, max_length=50, null=True)),
                ('flag', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='TipoDeGasto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('codigo', models.CharField(max_length=50)),
                ('tipo', models.CharField(choices=[('Por separado', 'Por separado'), ('A todo costo', 'A todo costo')], max_length=20)),
                ('responsable', models.CharField(max_length=50)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('centro_de_costos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='centro_costos.centrodecostos')),
            ],
        ),
        migrations.CreateModel(
            name='Gasto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=100)),
                ('fecha', models.DateField()),
                ('detalle', models.TextField()),
                ('documento', models.CharField(blank=True, max_length=100, null=True)),
                ('debe', models.DecimalField(decimal_places=2, max_digits=10)),
                ('haber', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('actividad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='centro_costos.actividad')),
                ('tipo_gasto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='centro_costos.tipodegasto')),
            ],
        ),
    ]
