# Generated by Django 5.0.14 on 2025-08-03 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('centro_costos', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Gasto',
            new_name='GastoTA2020',
        ),
    ]
