# Generated by Django 5.0.14 on 2025-09-01 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('centro_costos', '0002_rename_gasto_gastota2020'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gaston2',
            name='actividad',
        ),
    ]
