# Generated by Django 5.0.14 on 2025-09-03 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centro_costos', '0003_remove_gaston2_actividad'),
    ]

    operations = [
        migrations.AddField(
            model_name='gaston2',
            name='es_ingreso',
            field=models.BooleanField(default=False),
        ),
    ]
