# Generated by Django 5.0.14 on 2025-09-24 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centro_costos', '0004_gaston2_es_ingreso'),
    ]

    operations = [
        migrations.AddField(
            model_name='gaston2',
            name='editor',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='gaston2',
            name='fecha_registro',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='gaston2',
            name='ultima_modificacion',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
