# Generated by Django 5.0.14 on 2025-09-24 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centro_costos', '0005_gaston2_editor_gaston2_fecha_registro_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gaston8',
            old_name='actividad',
            new_name='editor',
        ),
        migrations.AddField(
            model_name='gaston8',
            name='es_ingreso',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='gaston8',
            name='fecha_registro',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='gaston8',
            name='ultima_modificacion',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
