# Generated by Django 5.0.14 on 2025-09-26 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centro_costos', '0007_rename_actividad_gaston1_editor_gaston1_es_ingreso_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gaston3',
            name='actividad',
        ),
        migrations.AddField(
            model_name='gaston3',
            name='editor',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='gaston3',
            name='es_ingreso',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='gaston3',
            name='fecha_registro',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='gaston3',
            name='ultima_modificacion',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
