# Generated by Django 5.0.14 on 2025-09-26 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centro_costos', '0010_rename_actividad_gaston4_editor_gaston4_es_ingreso_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gaston5',
            old_name='actividad',
            new_name='editor',
        ),
        migrations.AddField(
            model_name='gaston5',
            name='es_ingreso',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='gaston5',
            name='fecha_registro',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='gaston5',
            name='ultima_modificacion',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
