# Generated by Django 5.0.14 on 2025-09-26 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centro_costos', '0011_rename_actividad_gaston5_editor_gaston5_es_ingreso_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gaston6',
            old_name='actividad',
            new_name='editor',
        ),
        migrations.AddField(
            model_name='gaston6',
            name='es_ingreso',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='gaston6',
            name='fecha_registro',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='gaston6',
            name='ultima_modificacion',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
