# Generated by Django 5.0.14 on 2025-11-11 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centro_costos', '0012_rename_actividad_gaston6_editor_gaston6_es_ingreso_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gaston9',
            old_name='actividad',
            new_name='concepto',
        ),
        migrations.RenameField(
            model_name='gaston9',
            old_name='codigo',
            new_name='demandado',
        ),
        migrations.RenameField(
            model_name='gaston9',
            old_name='detalle',
            new_name='escrito',
        ),
        migrations.RemoveField(
            model_name='gaston9',
            name='referencia',
        ),
        migrations.RemoveField(
            model_name='gaston9',
            name='tipo_gasto',
        ),
        migrations.AddField(
            model_name='gaston9',
            name='demandante',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='gaston9',
            name='expediente',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='gaston9',
            name='juzgado',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='gaston9',
            name='materia',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='gaston2',
            name='pdf',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to='gastosCC'),
        ),
    ]
