# Generated by Django 5.0.14 on 2025-11-11 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centro_costos', '0013_rename_actividad_gaston9_concepto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gaston9',
            name='demandado',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='gaston9',
            name='demandante',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='gaston9',
            name='expediente',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='gaston9',
            name='juzgado',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='gaston9',
            name='materia',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
