# Generated by Django 5.0.14 on 2025-10-04 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CantaCallao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proyecto', models.CharField(max_length=255)),
                ('presupuesto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('sustento', models.TextField(blank=True, null=True)),
                ('fecha', models.DateField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Canta Callao',
                'verbose_name_plural': 'Canta Callao',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
