# Generated by Django 5.0.14 on 2025-10-04 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('canta_callao', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CantaCallao',
            new_name='Proyecto',
        ),
        migrations.AlterModelOptions(
            name='proyecto',
            options={'ordering': ['-fecha_creacion'], 'verbose_name': 'Proyecto Canta Callao', 'verbose_name_plural': 'Proyectos Canta Callao'},
        ),
    ]
