# Generated by Django 5.0.14 on 2025-10-04 21:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canta_callao', '0002_rename_cantacallao_proyecto_alter_proyecto_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='sustento',
            field=models.FileField(blank=True, null=True, upload_to='Proyecto_CantaCallao/'),
        ),
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=255)),
                ('sustento', models.FileField(blank=True, null=True, upload_to='Proyecto_CantaCallao/')),
                ('fecha', models.DateField()),
                ('debe', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('haber', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('saldo', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actividades', to='canta_callao.proyecto')),
            ],
            options={
                'verbose_name': 'Actividad',
                'verbose_name_plural': 'Actividades',
                'ordering': ['-fecha'],
            },
        ),
    ]
