# Generated by Django 5.0.14 on 2025-10-08 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canta_callao', '0003_alter_proyecto_sustento_actividad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actividad',
            name='debe',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='actividad',
            name='haber',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='actividad',
            name='saldo',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True),
        ),
    ]
