# Generated by Django 5.0.14 on 2025-10-31 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('canta_callao', '0004_alter_actividad_debe_alter_actividad_haber_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Actividad',
        ),
        migrations.DeleteModel(
            name='Proyecto',
        ),
    ]
