# Generated by Django 5.0.14 on 2025-11-22 17:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=10, null=True)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('dni', models.CharField(blank=True, max_length=100, null=True)),
                ('telefono', models.CharField(blank=True, max_length=255, null=True)),
                ('direccion', models.CharField(blank=True, max_length=50, null=True)),
                ('alergias_conocidas', models.CharField(blank=True, max_length=255, null=True)),
                ('emfermedades_previas', models.CharField(blank=True, max_length=255, null=True)),
                ('antecentes_quirurgicos', models.CharField(blank=True, max_length=255, null=True)),
                ('antecedentes_familiares', models.CharField(blank=True, max_length=255, null=True)),
                ('medicamentos_actuales', models.CharField(blank=True, max_length=255, null=True)),
                ('habitos', models.CharField(blank=True, max_length=255, null=True)),
                ('relato_clinico', models.TextField(blank=True, null=True)),
                ('peso', models.CharField(blank=True, max_length=50, null=True)),
                ('altura', models.CharField(blank=True, max_length=50, null=True)),
                ('presion_arterial', models.CharField(blank=True, max_length=50, null=True)),
                ('frecuencia_cardiaca', models.CharField(blank=True, max_length=50, null=True)),
                ('frecuencia_respiratoria', models.CharField(blank=True, max_length=50, null=True)),
                ('temperatura', models.CharField(blank=True, max_length=50, null=True)),
                ('tipo_de_sangre', models.CharField(blank=True, max_length=10, null=True)),
                ('descripcion_examen_fisico', models.TextField(blank=True, null=True)),
                ('nombre_contacto_emergencia1', models.CharField(blank=True, max_length=100, null=True)),
                ('telefono_contacto_emergencia1', models.CharField(blank=True, max_length=15, null=True)),
                ('relacion_contacto_emergencia1', models.CharField(blank=True, max_length=50, null=True)),
                ('nombre_contacto_emergencia2', models.CharField(blank=True, max_length=100, null=True)),
                ('telefono_contacto_emergencia2', models.CharField(blank=True, max_length=15, null=True)),
                ('relacion_contacto_emergencia2', models.CharField(blank=True, max_length=50, null=True)),
                ('nombre_contacto_emergencia3', models.CharField(blank=True, max_length=100, null=True)),
                ('telefono_contacto_emergencia3', models.CharField(blank=True, max_length=15, null=True)),
                ('relacion_contacto_emergencia3', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('motivo', models.CharField(max_length=255)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='citas', to='clinica.paciente')),
            ],
        ),
        migrations.CreateModel(
            name='RespuestaCita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diagnostico', models.TextField(blank=True, null=True)),
                ('tratamiento', models.TextField(blank=True, null=True)),
                ('notas', models.TextField(blank=True, null=True)),
                ('receta', models.TextField(blank=True, null=True)),
                ('cita', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='respuesta', to='clinica.cita')),
            ],
        ),
    ]
