# Generated by Django 5.0.14 on 2025-11-29 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0002_cita_created_at_cita_updated_at_paciente_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='estado',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='tipo_de_sangre',
            field=models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=10, null=True),
        ),
    ]
