# Generated by Django 5.0.14 on 2026-01-11 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0003_paciente_fecha_nacimiento'),
    ]

    operations = [
        migrations.AddField(
            model_name='respuestacita',
            name='alergias_conocidas',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='respuestacita',
            name='altura',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='respuestacita',
            name='antecedentes_familiares',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='respuestacita',
            name='antecentes_quirurgicos',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='respuestacita',
            name='descripcion_examen_fisico',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='respuestacita',
            name='emfermedades_previas',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='respuestacita',
            name='frecuencia_cardiaca',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='respuestacita',
            name='frecuencia_respiratoria',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='respuestacita',
            name='habitos',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='respuestacita',
            name='medicamentos_actuales',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='respuestacita',
            name='peso',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='respuestacita',
            name='presion_arterial',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='respuestacita',
            name='relato_clinico',
            field=models.TextField(blank=True, null=True),
        ),
    ]
