# Generated by Django 5.0.14 on 2025-11-29 21:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0003_cita_estado_alter_paciente_tipo_de_sangre'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImagenRespuestaCita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='respuesta_cita/imagenes/')),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('respuesta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='clinica.respuestacita')),
            ],
        ),
    ]
