# Generated by Django 5.0.14 on 2025-11-30 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0004_imagenrespuestacita'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='edad',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
