# Generated by Django 5.0.14 on 2025-11-30 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0005_paciente_edad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='nombre',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
