# Generated by Django 5.0.14 on 2025-06-05 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partidas_planos', '0003_alter_user_email_alter_user_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partida',
            name='pg',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
