# Generated by Django 5.0.14 on 2025-07-31 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partidas_planos', '0006_alter_partida_centro_costos_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Contabilidad'), (2, 'Legal'), (3, 'Administrador')], null=True),
        ),
    ]
