# Generated by Django 5.0.14 on 2025-09-30 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partidas_planos', '0008_user_saldo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='saldo',
            field=models.DecimalField(blank=True, decimal_places=2, default=100.0, max_digits=10, null=True),
        ),
    ]
