# Generated by Django 5.0.14 on 2025-05-20 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Anios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio', models.CharField(blank=True, max_length=50, null=True)),
                ('url', models.CharField(blank=True, max_length=50, null=True)),
                ('flag', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Q1_T1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_vencimiento', models.DateField(verbose_name='Fecha de Vencimiento')),
                ('proveedor', models.CharField(max_length=255, verbose_name='Proveedor')),
                ('concepto', models.TextField(verbose_name='Concepto')),
                ('soles', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Monto en Soles')),
                ('dolares', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Monto en Dólares')),
            ],
        ),
    ]
