# Generated by Django 5.0.14 on 2025-05-20 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hoja_requerimiento', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='q1_t1',
            name='quincena',
            field=models.CharField(choices=[('quincena1', 'quincena1'), ('quincena2', 'quincena2')], default=1, max_length=10, verbose_name='Quincena'),
            preserve_default=False,
        ),
    ]
