# Generated by Django 5.0.14 on 2025-05-20 18:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hoja_requerimiento', '0002_q1_t1_quincena'),
    ]

    operations = [
        migrations.AddField(
            model_name='q1_t1',
            name='anio',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='gastos', to='hoja_requerimiento.anios', verbose_name='Año'),
            preserve_default=False,
        ),
    ]
