# Generated by Django 5.0.14 on 2025-05-21 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hoja_requerimiento', '0003_q1_t1_anio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='q1_t1',
            name='quincena',
            field=models.BooleanField(default=False),
        ),
    ]
