# Generated by Django 5.0.14 on 2025-11-17 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productividad', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailyactivity',
            name='category',
        ),
        migrations.DeleteModel(
            name='ActivityCategory',
        ),
    ]
